import { useState } from "react";
import { BrandMark } from "@/components/brand-mark";
import { brand } from "@/config/brand";
import { chartSections, today } from "@/data/mock-profile";

const cards = [
  { name:"今日主句", eyebrow:"TODAY'S ORBIT", text:today.sentence },
  { name:"核心人格", eyebrow:"INNER MAP · 核心人格", text:"清醒、敏锐，也有自己的温度。" },
  { name:"人生主题", eyebrow:"INNER MAP · 人生主题", text:chartSections[5].text },
];
function makeSvg(card: typeof cards[number]) { const escape = (str:string) => str.replace(/[&<>"']/g, (m) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&apos;"}[m] || m)); const lines = card.text.match(/.{1,14}/g) || [card.text]; return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1420" viewBox="0 0 1080 1420"><rect width="1080" height="1420" fill="#25344b"/><ellipse cx="910" cy="460" rx="430" ry="150" fill="none" stroke="#ffffff" stroke-opacity=".27" stroke-width="2" transform="rotate(-28 910 460)"/><ellipse cx="860" cy="500" rx="270" ry="270" fill="none" stroke="#ffffff" stroke-opacity=".2" stroke-width="2"/><text x="80" y="105" font-family="Arial,sans-serif" font-size="25" fill="#f9f5ed" letter-spacing="8">NEXUS</text><text x="80" y="166" font-family="Arial,sans-serif" font-size="18" fill="#d6d2c8" letter-spacing="5">${escape(card.eyebrow)}</text>${lines.map((line, i) => `<text x="80" y="${470 + i * 90}" font-family="serif" font-size="64" fill="#f9f5ed">${escape(line)}</text>`).join("")}<line x1="80" y1="1240" x2="1000" y2="1240" stroke="#ffffff" stroke-opacity=".3"/><text x="80" y="1305" font-family="Arial,sans-serif" font-size="22" fill="#d6d2c8" letter-spacing="4">INNER ORBIT</text></svg>`; }
export function SharePage() { const [selected, setSelected] = useState(0); const [copied, setCopied] = useState(false); const card = cards[selected]; const download = () => { const url = URL.createObjectURL(new Blob([makeSvg(card)], {type:"image/svg+xml"})); const a=document.createElement("a");a.href=url;a.download=`${brand.name.toLowerCase()}-${selected + 1}.svg`;a.click();URL.revokeObjectURL(url); }; const copy=async()=>{await navigator.clipboard.writeText(card.text);setCopied(true);setTimeout(()=>setCopied(false),1800);}; return <section className="page"><BrandMark /><p className="eyebrow" style={{marginTop:38}}>SAVE A MOMENT</p><h1 className="display" style={{fontSize:32,margin:"8px 0 22px"}}>分享你的观察</h1><div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:5}}>{cards.map((item,index)=><button key={item.name} className={index===selected?"primary":"secondary"} style={{minHeight:39,borderRadius:20,whiteSpace:"nowrap",fontSize:13}} onClick={()=>setSelected(index)}>{item.name}</button>)}</div><div className="share-card" style={{margin:"25px 0"}}><BrandMark light /><p style={{fontSize:11,letterSpacing:".12em",opacity:.75,marginTop:36}}>{card.eyebrow}</p><p className="display" style={{fontSize:selected===2?26:34,lineHeight:1.42,maxWidth:"92%",zIndex:1,marginTop:"auto",marginBottom:95}}>{card.text}</p><div style={{position:"absolute",bottom:24,left:25,fontSize:11,letterSpacing:".16em",opacity:.8}}>{brand.subtitle}</div></div><button className="primary" style={{width:"100%"}} onClick={download}>保存为图片</button><button className="secondary" style={{width:"100%",marginTop:10}} onClick={copy}>{copied ? "已复制" : "复制文字"}</button><p className="muted" style={{fontSize:12,lineHeight:1.6,textAlign:"center"}}>将导出为高清 SVG 图片，可保存或分享。</p></section>; }
